package com.bdc.analytics;
import com.bdc.dto.Models.*;import com.bdc.provider.BusinessDataProvider;import org.springframework.stereotype.Service;
import java.time.*;import java.time.temporal.ChronoUnit;import java.util.*;import java.util.function.Function;import java.math.*;import java.util.stream.*;
@Service public class AnalyticsEngine {
 private final BusinessDataProvider provider;
 public AnalyticsEngine(BusinessDataProvider p){provider=p;}
 public LocalDate end(){return provider.load().items().stream().map(Sale::date).max(LocalDate::compareTo).orElseThrow().withDayOfMonth(1).plusMonths(1).minusDays(1);}
 public Filter defaults(){return new Filter(end().minusMonths(11).withDayOfMonth(1),end(),null,null,null,null,null);}
 public List<Sale> select(Filter f){return provider.load().items().stream().filter(s->!s.date().isBefore(f.from())&&!s.date().isAfter(f.to())).filter(s->match(f.country(),s.country())&&match(f.region(),s.region())&&match(f.customer(),s.customerId())&&match(f.product(),s.productId())&&match(f.businessUnit(),s.businessUnit())).toList();}
 private boolean match(String f,String v){return f==null||f.isBlank()||f.equalsIgnoreCase(v);}
 public BigDecimal sum(List<Sale> s,boolean cost){return s.stream().map(cost?Sale::cost:Sale::revenue).reduce(BigDecimal.ZERO,BigDecimal::add);}
 public BigDecimal percent(BigDecimal a,BigDecimal b){return b.signum()==0?null:a.subtract(b).multiply(BigDecimal.valueOf(100)).divide(b,2,RoundingMode.HALF_UP);}
 public Map<String,BigDecimal> getProfitMargin(Filter f){var s=select(f);var r=sum(s,false);var c=sum(s,true);long orders=s.stream().map(Sale::orderId).distinct().count();var m=new LinkedHashMap<String,BigDecimal>();m.put("revenue",r);m.put("orders",BigDecimal.valueOf(orders));m.put("customers",BigDecimal.valueOf(s.stream().map(Sale::customerId).distinct().count()));m.put("averageOrderValue",orders==0?BigDecimal.ZERO:r.divide(BigDecimal.valueOf(orders),2,RoundingMode.HALF_UP));m.put("grossProfit",r.subtract(c));m.put("profitMargin",r.signum()==0?BigDecimal.ZERO:r.subtract(c).multiply(BigDecimal.valueOf(100)).divide(r,2,RoundingMode.HALF_UP));return m;}
 public List<Row> group(Filter f,Function<Sale,String> key){return select(f).stream().collect(Collectors.groupingBy(key,TreeMap::new,Collectors.toList())).entrySet().stream().map(e->new Row(e.getKey(),sum(e.getValue(),false),sum(e.getValue(),true),e.getValue().stream().map(Sale::orderId).distinct().count(),null,null)).toList();}
 public List<Row> getRevenueByPeriod(Filter f){var grouped=group(f,s->YearMonth.from(s.date()).toString());var map=grouped.stream().collect(Collectors.toMap(Row::label,Function.identity()));var rows=new ArrayList<Row>();for(YearMonth m=YearMonth.from(f.from());!m.isAfter(YearMonth.from(f.to()));m=m.plusMonths(1))rows.add(map.getOrDefault(m.toString(),new Row(m.toString(),BigDecimal.ZERO,BigDecimal.ZERO,0,null,null)));return rows;}
 public List<Row> getRevenueByCountry(Filter f){return group(f,Sale::country);}
 public List<Row> getRevenueByRegion(Filter f){return group(f,Sale::region);}
 public List<Row> getTopCustomers(Filter f){return top(group(f,s->s.customerId()+" · "+s.customer()));}
 public List<Row> getTopProducts(Filter f){return top(group(f,s->s.productId()+" · "+s.product()));}
 private List<Row> top(List<Row> rows){return rows.stream().sorted(Comparator.comparing(Row::revenue).reversed()).limit(10).toList();}
 public Filter previous(Filter f){long months=ChronoUnit.MONTHS.between(YearMonth.from(f.from()),YearMonth.from(f.to()))+1;return new Filter(f.from().minusMonths(months),f.from().minusDays(1),f.country(),f.region(),f.customer(),f.product(),f.businessUnit());}
 public List<Row> comparePeriods(Filter f){var now=getProfitMargin(f);var before=getProfitMargin(previous(f));return List.of(new Row("Revenue",now.get("revenue"),now.get("revenue").subtract(now.get("grossProfit")),now.get("orders").longValue(),before.get("revenue"),percent(now.get("revenue"),before.get("revenue"))));}
 public List<Row> compareCountries(Filter f,List<String> countries){return changes(f,Sale::country,false).stream().filter(r->countries.isEmpty()||countries.contains(r.label())).toList();}
 public List<Row> getDecliningProducts(Filter f){return changes(f,s->s.productId()+" · "+s.product(),false).stream().filter(r->r.change()!=null&&r.change().signum()<0).sorted(Comparator.comparing(Row::change)).toList();}
 public List<Row> getCustomerOrderTrend(Filter f){return changes(f,s->s.customerId()+" · "+s.customer(),true).stream().filter(r->r.change()!=null&&r.change().compareTo(BigDecimal.valueOf(-20))<0).sorted(Comparator.comparing(Row::change)).toList();}
 private List<Row> changes(Filter f,Function<Sale,String> key,boolean count){var current=group(f,key).stream().collect(Collectors.toMap(Row::label,Function.identity()));var before=group(previous(f),key).stream().collect(Collectors.toMap(Row::label,Function.identity()));var labels=new TreeSet<>(current.keySet());labels.addAll(before.keySet());return labels.stream().map(k->{var a=current.getOrDefault(k,new Row(k,BigDecimal.ZERO,BigDecimal.ZERO,0,null,null));var b=before.getOrDefault(k,new Row(k,BigDecimal.ZERO,BigDecimal.ZERO,0,null,null));BigDecimal av=count?BigDecimal.valueOf(a.orders()):a.revenue(),bv=count?BigDecimal.valueOf(b.orders()):b.revenue();return new Row(k,a.revenue(),a.cost(),a.orders(),bv,percent(av,bv));}).toList();}
 public Chart chart(List<Row> rows,String type){return new Chart(type,rows.stream().map(Row::label).toList(),List.of(new Series("Revenue (USD)",rows.stream().map(Row::revenue).toList())));}
 public Map<String,Object> dashboard(Filter f){var m=new LinkedHashMap<String,Object>();m.put("metrics",getProfitMargin(f));m.put("monthly",getRevenueByPeriod(f));m.put("countries",getRevenueByCountry(f));m.put("units",group(f,Sale::businessUnit));m.put("products",getTopProducts(f));m.put("customers",getTopCustomers(f));m.put("insights",insights(f));m.put("dataSource",provider.source());return m;}
 public List<String> insights(Filter f){var out=new ArrayList<String>();var r=comparePeriods(f).get(0);out.add(r.change()==null?"No prior revenue is available for this period.":"Revenue changed "+r.change()+"% versus "+previous(f).from()+" to "+previous(f).to()+".");getDecliningProducts(f).stream().findFirst().ifPresent(p->out.add(p.label()+" revenue declined "+p.change().abs()+"% versus the preceding equal-length period."));getCustomerOrderTrend(f).stream().findFirst().ifPresent(c->out.add(c.label()+" order count fell "+c.change().abs()+"%."));return out;}
 public Map<String,Object> catalog(){return Map.of("customers",provider.load().customers(),"products",provider.load().products(),"countries",List.of("India","Germany","USA","UAE","UK"),"regions",List.of("Asia Pacific","Europe","North America","Middle East"),"businessUnits",List.of("Cloud & Software","Industrial Systems","Business Services"),"from","2024-09-01","to",end().toString(),"transactions",provider.load().items().size());}
}
