package com.bdc;
import com.bdc.analytics.AnalyticsEngine;import com.bdc.provider.*;import com.bdc.dto.Models.*;import org.junit.jupiter.api.*;import static org.junit.jupiter.api.Assertions.*;import java.util.*;import java.time.*;import java.math.*;
class AnalyticsEngineTest {
 AnalyticsEngine engine;Filter current=new Filter(LocalDate.of(2026,4,1),LocalDate.of(2026,6,30),null,null,null,null,null);
 Sale sale(String id,String customer,String product,String country,String date,String revenue,String cost){return new Sale(id,customer,customer,product,product,country,"Region","Unit",LocalDate.parse(date),1,new BigDecimal(revenue),new BigDecimal(cost));}
 @BeforeEach void setup(){var sales=List.of(sale("1","A","P1","India","2026-01-15","100","60"),sale("2","B","P2","Germany","2026-02-15","200","120"),sale("3","A","P1","India","2026-04-01","80","40"),sale("4","B","P2","Germany","2026-06-30","300","180"));engine=new AnalyticsEngine(new BusinessDataProvider(){public DataSet load(){return new DataSet(List.of(),List.of(),List.of(),sales,List.of());}public String source(){return "fixture";}});}
 @Test void revenueAndMargin(){var m=engine.getProfitMargin(current);assertEquals(0,new BigDecimal("380").compareTo(m.get("revenue")));assertEquals(0,new BigDecimal("160").compareTo(m.get("grossProfit")));assertEquals(new BigDecimal("42.11"),m.get("profitMargin"));assertEquals(new BigDecimal("190.00"),m.get("averageOrderValue"));}
 @Test void countryComparison(){var rows=engine.compareCountries(current,List.of("India","Germany"));assertEquals(2,rows.size());assertEquals(new BigDecimal("50.00"),rows.get(0).change());assertEquals(new BigDecimal("-20.00"),rows.get(1).change());}
 @Test void periodComparison(){var r=engine.comparePeriods(current).get(0);assertEquals(new BigDecimal("300"),r.previous());assertEquals(new BigDecimal("26.67"),r.change());}
 @Test void topCustomers(){assertEquals("B · B",engine.getTopCustomers(current).get(0).label());}
 @Test void decliningProducts(){var rows=engine.getDecliningProducts(current);assertEquals(1,rows.size());assertEquals("P1 · P1",rows.get(0).label());assertEquals(new BigDecimal("-20.00"),rows.get(0).change());}
 @Test void emptyAndZeroBaseline(){Filter f=new Filter(LocalDate.of(2023,1,1),LocalDate.of(2023,3,31),null,null,null,null,null);assertEquals(BigDecimal.ZERO,engine.getProfitMargin(f).get("profitMargin"));assertNull(engine.comparePeriods(f).get(0).change());assertEquals(3,engine.getRevenueByPeriod(f).size());}
 @Test void filterAndInclusiveBounds(){Filter f=new Filter(current.from(),current.to(),"India",null,null,null,null);assertEquals(new BigDecimal("80"),engine.getProfitMargin(f).get("revenue"));assertEquals(2,engine.select(current).size());}
 @Test void mockDataIntegrity(){var d=new MockBusinessDataProvider().load();assertEquals(100,d.customers().size());assertEquals(50,d.products().size());assertTrue(d.items().size()>1000);assertEquals(24,d.items().stream().map(s->YearMonth.from(s.date())).distinct().count());assertEquals(d.orders().size(),d.invoices().size());assertEquals(new MockBusinessDataProvider().load(),d);assertTrue(d.items().stream().allMatch(s->s.revenue().compareTo(s.cost())>0));}
}
