package com.bdc;
import org.junit.jupiter.api.*;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.test.web.servlet.MockMvc;import org.springframework.http.MediaType;import com.fasterxml.jackson.databind.*;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;import static org.junit.jupiter.api.Assertions.*;
@SpringBootTest(properties={"spring.datasource.url=jdbc:h2:mem:test;MODE=MySQL","spring.jpa.hibernate.ddl-auto=create-drop"}) @AutoConfigureMockMvc class ApiTest {
 @Autowired MockMvc mvc;@Autowired ObjectMapper json;
 JsonNode ask(String q,String id)throws Exception{String body=json.writeValueAsString(new com.bdc.dto.Models.ChatRequest(q,id));String response=mvc.perform(post("/api/chat").contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isOk()).andExpect(jsonPath("$.dataSource").value("Mock SAP Business Data Cloud")).andReturn().getResponse().getContentAsString();return json.readTree(response);}
 @Test void fiveDemoQuestions()throws Exception{
  String[] qs={"Show revenue for the last 12 months.","Compare India and Germany sales.","Show the top 10 customers.","Which products are declining?","Why did revenue change last quarter?"};
  String[] functions={"getRevenueByPeriod","compareCountries","getTopCustomers","getDecliningProducts","comparePeriods"};
  for(int i=0;i<qs.length;i++){var r=ask(qs[i],null);assertEquals(functions[i],r.get("function").asText());assertFalse(r.get("table").isEmpty());assertFalse(r.get("answer").asText().isBlank());if(i==0)assertEquals(12,r.get("table").size());if(i==1)assertEquals(2,r.get("table").size());if(i==2)assertEquals(10,r.get("table").size());}
 }
 @Test void followUpRetainsCountryAndPeriod()throws Exception{var first=ask("Compare India and Germany sales for the last 6 months.",null);var second=ask("Why is India growing faster?",first.get("conversationId").asText());assertEquals(first.get("period"),second.get("period"));assertEquals(first.get("table"),second.get("table"));assertEquals(2,second.get("table").size());mvc.perform(get("/api/conversations/"+first.get("conversationId").asText())).andExpect(status().isOk()).andExpect(jsonPath("$.length()").value(2));}
 @Test void rejectInvalidAndHandleUnknown()throws Exception{mvc.perform(post("/api/chat").contentType(MediaType.APPLICATION_JSON).content("{\"question\":\"\"}")).andExpect(status().isBadRequest());assertEquals("UNSUPPORTED",ask("DROP TABLE sales",null).get("intent").asText());mvc.perform(get("/api/dashboard?from=2026-08-01&to=2026-01-01")).andExpect(status().isBadRequest());}
}
